                      ORG $0F8000                         ;;                   ;
                                                          ;;                   ;
MusicSamples:         dw SampleData-MusicSamples-4        ;;----|8000/----\----;
                      dw !SamplePtrTable                  ;;----|8002/----\----;
                                                          ;;                   ;
                      dw Sample00                         ;;----|8004/----\----;
                      dw Sample01                         ;;----|8006/----\----;
                      dw Sample02                         ;;----|8008/----\----;
                      dw Sample03                         ;;----|800A/----\----;
                      dw Sample04                         ;;----|800C/----\----;
                      dw Sample05                         ;;----|800E/----\----;
                      dw Sample06                         ;;----|8010/----\----;
                      dw Sample07                         ;;----|8012/----\----;
                      dw Sample08                         ;;----|8014/----\----;
                      dw Sample09                         ;;----|8016/----\----;
                      dw Sample0A                         ;;----|8018/----\----;
                      dw Sample0B                         ;;----|801A/----\----;
                      dw Sample0C                         ;;----|801C/----\----;
                      dw Sample0C                         ;;----|801C/----\----;
                      dw Sample0D                         ;;----|801E/----\----;
                      dw Sample0E                         ;;----|8020/----\----;
                      dw Sample0F                         ;;----|8022/----\----;
                      dw Sample10                         ;;----|8024/----\----;
                      dw Sample11                         ;;----|8026/----\----;
                      dw Sample12                         ;;----|8028/----\----;
                      dw Sample13                         ;;----|802A/----\----;
                      dw Sample13                         ;;----|802A/----\----;
                      dw Sample14                         ;;----|802C/----\----;
                      dw Sample14                         ;;----|802C/----\----;
                      dw Sample15                         ;;----|802E/----\----;
                      dw Sample16                         ;;----|8030/----\----;
                      dw Sample17                         ;;----|8032/----\----;
                      dw Sample18                         ;;----|8034/----\----;
                      dw Sample19                         ;;----|8036/----\----;
                      dw Sample1A                         ;;----|8038/----\----;
                      dw Sample1B                         ;;----|803A/----\----;
                      dw Sample1B                         ;;----|803A/----\----;
                      dw Sample1C                         ;;----|803C/----\----;
                      dw Sample1C                         ;;----|803C/----\----;
                      dw Sample1D                         ;;----|803E/----\----;
                      dw Sample1E                         ;;----|8040/----\----;
                      dw Sample1F                         ;;----|8042/----\----;
                      dw Sample1F                         ;;----|8042/----\----;
                      dw Sample20                         ;;----|8044/----\----;
                      dw Sample20                         ;;----|8044/----\----;
                                                          ;;                   ;
SampleData:           dw SampleData_End-SampleData-4      ;;----|8054/----\----;
                      dw !SampleTable                     ;;----|8056/----\----;
                                                          ;;                   ;
                      base !SampleTable                   ;;                   ;
Sample00:                                                 ;;                   ;
                      incbin "samples/Sample00.brr"       ;;----|8058/----\----;
Sample01:                                                 ;;                   ;
                      incbin "samples/Sample01.brr"       ;;----|807C/----\----;
Sample02:                                                 ;;                   ;
                      incbin "samples/Sample02.brr"       ;;----|8097/----\----;
Sample03:                                                 ;;                   ;
                      incbin "samples/Sample03.brr"       ;;----|80BB/----\----;
Sample04:                                                 ;;                   ;
                      incbin "samples/Sample04.brr"       ;;----|80D6/----\----;
Sample05:                                                 ;;                   ;
                      incbin "samples/Sample05.brr"       ;;----|81C0/----\----;
Sample06:                                                 ;;                   ;
                      incbin "samples/Sample06.brr"       ;;----|81DB/----\----;
Sample07:                                                 ;;                   ;
                      incbin "samples/Sample07.brr"       ;;----|8304/----\----;
Sample08:                                                 ;;                   ;
                      incbin "samples/Sample08.brr"       ;;----|831F/----\----;
Sample09:                                                 ;;                   ;
                      incbin "samples/Sample09.brr"       ;;----|8343/----\----;
Sample0A:                                                 ;;                   ;
                      incbin "samples/Sample0A.brr"       ;;----|835E/----\----;
Sample0B:                                                 ;;                   ;
                      incbin "samples/Sample0B.brr"       ;;----|8487/----\----;
Sample0C:                                                 ;;                   ;
                      incbin "samples/Sample0C.brr"       ;;----|8595/----\----;
Sample0D:                                                 ;;                   ;
                      incbin "samples/Sample0D.brr"       ;;----|8A03/----\----;
Sample0E:                                                 ;;                   ;
                      incbin "samples/Sample0E.brr"       ;;----|902A/----\----;
Sample0F:                                                 ;;                   ;
                      incbin "samples/Sample0F.brr"       ;;----|9069/----\----;
Sample10:                                                 ;;                   ;
                      incbin "samples/Sample10.brr"       ;;----|908D/----\----;
Sample11:                                                 ;;                   ;
                      incbin "samples/Sample11.brr"       ;;----|90A8/----\----;
Sample12:                                                 ;;                   ;
                      incbin "samples/Sample12.brr"       ;;----|9CD2/----\----;
Sample13:                                                 ;;                   ;
                      incbin "samples/Sample13.brr"       ;;----|9CED/----\----;
Sample14:                                                 ;;                   ;
                      incbin "samples/Sample14.brr"       ;;----|AF6B/----\----;
Sample15:                                                 ;;                   ;
                      incbin "samples/Sample15.brr"       ;;----|B607/----\----;
Sample16:                                                 ;;                   ;
                      incbin "samples/Sample16.brr"       ;;----|B62B/----\----;
Sample17:                                                 ;;                   ;
                      incbin "samples/Sample17.brr"       ;;----|B646/----\----;
Sample18:                                                 ;;                   ;
                      incbin "samples/Sample18.brr"       ;;----|B8E0/----\----;
Sample19:                                                 ;;                   ;
                      incbin "samples/Sample19.brr"       ;;----|B91F/----\----;
Sample1A:                                                 ;;                   ;
                      incbin "samples/Sample1A.brr"       ;;----|C390/----\----;
Sample1B:                                                 ;;                   ;
                      incbin "samples/Sample1B.brr"       ;;----|C3AB/----\----;
Sample1C:                                                 ;;                   ;
                      incbin "samples/Sample1C.brr"       ;;----|C62A/----\----;
Sample1D:                                                 ;;                   ;
                      incbin "samples/Sample1D.brr"       ;;----|CF0F/----\----;
Sample1E:                                                 ;;                   ;
                      incbin "samples/Sample1E.brr"       ;;----|D41F/----\----;
Sample1F:                                                 ;;                   ;
                      incbin "samples/Sample1F.brr"       ;;----|D479/----\----;
Sample20:                                                 ;;                   ;
                      incbin "samples/Sample20.brr"       ;;----|DDD3/----\----;
                                                          ;;                   ;
                      base off                            ;;                   ;
                                                          ;;                   ;
SampleData_End:       dw $0000,!SPCEngine                 ;;----|EF78/----\----;
                                                          ;;                   ;
                      db $18,$00,$00,$00                  ;;----|EF7C/----\----;
                      db $00,$00,$00,$00,$00,$00,$00,$00  ;;----|EF80/----\----;
                      db $00,$00,$00,$00,$00,$00,$00,$00  ;;----|EF88/----\----;
                                                          ;;                   ;
                      padbyte $FF : pad $108000           ;;----|EF90/----\----;