%S_Header(0, 0, 0, "vertical")
%S_NetKoopa($003, $00D, "green", "leftright", "background")
%S_NetKoopa($009, $010, "green", "leftright", "background")
%S_NetKoopa($009, $013, "green", "leftright", "background")
%S_NetKoopa($003, $018, "red", "leftright", "background")
%S_NetKoopa($007, $01D, "red", "updown", "background")
%S_NetKoopa($00C, $01D, "green", "leftright", "foreground")
%S_NetKoopa($004, $01D, "green", "updown", "foreground")
%S_NetKoopa($01A, $021, "green", "leftright", "foreground")
%S_NetKoopa($014, $021, "green", "updown", "foreground")
%S_NetKoopa($00C, $021, "green", "leftright", "foreground")
%S_NetKoopa($014, $026, "green", "leftright", "foreground")
%S_NetKoopa($01A, $026, "green", "updown", "foreground")
%S_NetKoopa($00A, $026, "green", "updown", "foreground")
%S_NetKoopa($007, $027, "red", "updown", "background")
%S_NetKoopa($01A, $02B, "green", "leftright", "foreground")
%S_NetKoopa($014, $02B, "green", "updown", "foreground")
%S_NetKoopa($006, $02D, "green", "leftright", "foreground")
%S_NetKoopa($003, $02E, "green", "leftright", "background")
%S_NetKoopa($009, $034, "red", "updown", "background")
%S_NetKoopa($006, $034, "green", "updown", "foreground")
%S_NetKoopa($00B, $03C, "green", "leftright", "background")
%S_End()
